name: Metrics (Activity)
on:
  schedule:
    - cron: "15 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.25
        with:
          # data token
          token: ${{ secrets.METRICS_TOKEN }}

          # commit token (IMPORTANT: avoid 403)
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main

          user: arwinwijaya
          template: classic
          config_timezone: Asia/Jakarta

          # output
          filename: metrics-activity.svg
          output_action: commit

          # keep it light
          base: header

          # Disabled because the upstream activity plugin is currently brittle
          # with some GitHub event payloads and can fail with "unexpected error".
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          plugin_pagespeed: yes
          plugin_pagespeed_url: https://marwinwijaya.github.io
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}

          # reduce size / avoid huge base64
          config_output: svg
          config_display: regular

      - uses: lowlighter/metrics@v3.25
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main

          user: arwinwijaya
          template: classic
          config_timezone: Asia/Jakarta

          filename: metrics-classic.svg
          output_action: commit

          base: header, activity, community, repositories, metadata

          config_output: svg
          config_display: regular

      - uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main

          user: arwinwijaya
          template: classic
          config_timezone: Asia/Jakarta

          filename: metrics-stargazers-worldmap.svg
          output_action: commit

          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts: no
          plugin_stargazers_worldmap: yes
          plugin_stargazers_worldmap_token: ${{ secrets.GOOGLE_MAP_TOKEN }}
          plugin_stargazers_worldmap_sample: 200

          config_output: svg
          config_display: regular

      - uses: lowlighter/metrics@v3.25
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main

          user: GGF-Innovation-Team
          template: classic
          config_timezone: Asia/Jakarta

          filename: metrics-organization.svg
          output_action: commit

          base: header, activity, community, repositories, metadata

          config_output: svg
          config_display: regular
