name: Metrics (Chess)
on:
  schedule:
    - cron: "45 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  github-metrics-chess:
    runs-on: ubuntu-latest
    steps:
      - continue-on-error: true
        uses: lowlighter/metrics@master
        with:
          token: NOT_NEEDED
          committer_token: ${{ secrets.METRICS_TOKEN }}
          committer_branch: main

          user: arwinwijaya
          template: classic
          config_timezone: Asia/Jakarta

          filename: metrics-chess.svg
          output_action: commit

          base: ""
          plugin_chess: yes
          plugin_chess_token: ${{ secrets.CHESS_TOKEN }}
          plugin_chess_user: marwinwijaya
          plugin_chess_platform: lichess.org

          config_output: svg
          config_display: regular
